# overrides for development -
# dont ever copy to production machine!

# see doc: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.4'
services:
  module-handbook-postgres:
      environment:
        - POSTGRES_DB=modhand-db-dev # test?
      ports:
      - "5432:5432" # don't do this on production!
  module-handbook:
    build:
      context: .
      dockerfile: Dockerfile
      target: modhand-dev
    image: modulehandbook-local
# currently the same
#    ports:
#      - "3030:3000"
    volumes:
      - .:/module-handbook  # use app files from host
      - /module-handbook/node_modules # but not the node_modules
    environment:
      - POSTGRES_DB=modhand-db-dev
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=REMOVE
