version: '3.9'
services:
  module-handbook-mariadb-testci:
    container_name: modulehandbook-database-testci
    image: yobasystems/alpine-mariadb:10.6.11
    environment:
      - APPLICATION=module-handbook
      - MYSQL_ROOT_PASSWORD=modhand
      - MYSQL_DATABASE=modhand-db-testci

  module-handbook-exporter-testci:
    image: ghcr.io/modulehandbook/exporter:${TAG_MODULE_HANDBOOK_EXPORTER}
    container_name: modulehandbook-exporter-testci

  module-handbook-testci:
    image: modhand-testci:latest
    container_name: modulehandbook-testci
    environment:
      - TAG
      - RAILS_ENV=test
      - RAILS_DB_HOST="module-handbook-mariadb-testci"
      - MARIADB_USER=root
      - MARIADB_PASSWORD=modhand
      - MARIADB_DB=modhand-db-testci
      - RAILS_SERVE_STATIC_FILES=true
      - EXPORTER_BASE_URL=${EXPORTER_BASE_URL:-http://module-handbook-exporter:3030/}
      - DEVISE_EMAIL_HOSTNAME=${DEVISE_EMAIL_HOSTNAME}
      - DEVISE_EMAIL=${DEVISE_EMAIL}

  #  env_file:
  #    - ${SECRET_ENV_FILE}
    depends_on:
      - module-handbook-mariadb-testci
      - module-handbook-exporter-testci
    volumes:
      - ./container_logs:/module-handbook/log
      - ./container_tmp:/module-handbook/tmp
    restart: "no"
