# default configuration for production
# use .env file to differentiate between prod and dev
version: '3.4'
services:
  module-handbook-mariadb:
    container_name: modulehandbook-database
    image: yobasystems/alpine-mariadb:10.6.11
    environment:
      - APPLICATION=module-handbook
      - MYSQL_PASSWORD=modhand
      - MYSQL_USER=modhand
      - MYSQL_DATABASE=modhand-db-prod
    volumes:
      - ./mariadb_data:/var/lib/mysql
  module-handbook-exporter:
    image: ghcr.io/modulehandbook/exporter:${TAG_MODULE_HANDBOOK_EXPORTER}
    container_name: modulehandbook-exporter
  module-handbook:
    image: ghcr.io/modulehandbook/modulehandbook:${TAG_MODULE_HANDBOOK}
    container_name: modulehandbook
    environment:
      - TAG
      - RAILS_ENV=production
      - RAILS_DB_HOST="module-handbook-mariadb"
      - MARIADB_USER=modhand
      - MARIADB_PASSWORD=modhand
      - MARIADB_DB=modhand-db-prod
      - RAILS_SERVE_STATIC_FILES=true
      - EXPORTER_BASE_URL=${EXPORTER_BASE_URL:-http://module-handbook-exporter:3030/}
    env_file:
      - ${SECRET_ENV_FILE}
    depends_on:
      - module-handbook-mariadb
      - module-handbook-exporter
    volumes:
      - ./container_logs:/module-handbook/log
    restart: always
  nginx:
     image: nginx:latest
     container_name: reverse_proxy
     volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/templates:/etc/nginx/templates
         - ./container_logs/nginx:/var/log/nginx
         - ./secrets/nginx:/etc/ssl
     ports:
         - "80:80"
         - "443:443"
     environment:
        - NGINX_HOST=${NGINX_HOST:-localhost}
        - NGINX_CERT=${NGINX_CERT:-/etc/ssl/server.crt}
        - NGINX_KEY=${NGINX_KEY:-/etc/ssl/server.key}
        - NGINX_PORT=80
        - NGINX_SSL_PORT=443
        - NGINX_PROXY=http://module-handbook:3000
        - NGINX_ENTRYPOINT_QUIET_LOGS=1
     depends_on:
         - module-handbook
