# default configuration for production
version: '3.4'
services:
  module-handbook-postgres:
    container_name: modulehandbook-database
    image: postgres:13.4-alpine
#    container_name: module-handbook-postgres
    environment:
      - APPLICATION=module-handbook
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_USER=modhand
      - POSTGRES_DB=modhand-db-prod
# https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
      - POSTGRES_HOST_AUTH_METHOD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  module-handbook:
    image: ghcr.io/modulehandbook/modulehandbook:${TAG}
    container_name: modulehandbook
    environment:
      - TAG
      - RAILS_ENV=production
      - RAILS_DB_HOST="module-handbook-postgres"
      - POSTGRES_USER=modhand
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_DB=modhand-db-prod
      - RAILS_MASTER_KEY=EMPTY
      - RAILS_SERVE_STATIC_FILES=true
    depends_on:
      - module-handbook-postgres
    volumes:
      - ./logc:/usr/src/app/log
    ports:
      - 3030:3000
    restart: always
