version: '3.4'
services:
  module-handbook-postgres:
    image: postgres:13.4-alpine
#    container_name: module-handbook-postgres
    environment:
      - APPLICATION=module-handbook
      - POSTGRES_PASSWORD=modhand
      - POSTGRES_USER=modhand
      - POSTGRES_DB=modhand-dev
# https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - "5432:5432" # don't do this on production!
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  module-handbook:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - module-handbook-postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/module-handbook
    # env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_DB_HOST: module-handbook-postgres
      POSTGRES_USER: modhand
      POSTGRES_PASSWORD: modhand
      POSTGRES_DB: modhand-dev
