default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("MARIADB_USER") { 'modhand' } %>
  # heroku first, then compose file value:
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] || ENV.fetch("MARIADB_PASSWORD") { 'modhand' } %>
  port: <%= ENV.fetch("MARIADB_PORT") { 3306 } %>
  database: <%= ENV['MARIADB_DB'] || 'modhand-test' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
