default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'modhand' } %>
  # heroku first, then compose file value:
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] || ENV.fetch("POSTGRES_PASSWORD") { 'modhand' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: modhand-dev

test:
  <<: *default
  database: modhand-test

production:
  <<: *default
  # will heroku still work? https://devcenter.heroku.com/articles/heroku-postgresql
  #     url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: module_handbook_production
