name: Build and push Docker image compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      module-handbook-postgres:
        image: postgres:13.4-alpine
        env:
          APPLICATION: module-handbook
          POSTGRES_PASSWORD: modhand
          POSTGRES_USER: modhand
          POSTGRES_DB: modhand-db-prod
          POSTGRES_HOST_AUTH_METHOD: password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image (staging)
        # if: ${{ github.ref == 'refs/heads/master' && github.ref_type == 'branch'}} # only build and push if on master and triggered by branch
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          platforms: linux/amd64 # linux/arm64
          push: true
          tags: ${{ github.sha }}
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (release)
        if: ${{ github.ref == 'refs/heads/master' && github.ref_type == 'tag'}} # only build and push if on master and triggered by tag
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
