name: Pull Request
on:
  branches:
    - fix_tests

jobs:
  pull-request:
    name: Pipeline
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/pipeline.yml
    with:
      tags: type=ref,event=pr
      push: false
      target: modhand-prod-no-assets
