name: Production Pipeline
on:
  push:
    tags: [ '*' ]
    branches-ignore: [ '!master' ]

jobs:
  production:
     name: Release
     if: ${{ github.ref_type == 'tag' }}
     uses: ./.github/workflows/pipeline.yml
     with:
       tags: type=ref,event=tag
       push: true
