name: local-branch
on:
  push:
    branches: [ fix_tests ]
    tags-ignore: [ '*' ]

jobs:
  staging:
    name: Local Branch
    # if: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/master'}}
    uses: ./.github/workflows/pipeline.yml
    with:
      tags: type=sha
      push: false
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
