name: Test App

on:
  push:
    branches:
      - try_cuprite_driver
  workflow_call:
env:
  RAILS_DB_HOST: 127.0.0.1
  MARIADB_PORT: 3306
  MARIADB_USER: root
  MARIADB_PASSWORD: modhand
jobs:
  test:
    name: rails
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: modhand
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Install dependencies
        run: bundle install

      - name: create test db
        run: rails db:create RAILS_ENV=test

      - name: Run Tests
        id: run-tests
        run: rails test

      - name: Run System Tests
        id: test-system
        run: rails test:system

      - name: Echo Log
        if: ${{ failure() }}
        run: cat "log/test.log"

      - name: Some Info
        if: ${{ always() }}
        run: |
          ls -lart log
          less "log/test.log"
